### ISSUE TITLE
Deploy do bookdown

### ISSUE THREAD

**Issue by AdrianoPereira** [dataAt/introducao-analise-de-dados-espaciais#8]
Galera, fui fazer o deploy do site, acabei quebrando.
Fiz o merge do repositório principal com as alterações que fiz ontem, resolvi os conflitos, e subi pra branch **master**. Porém, ao subir pra branch **WIP-DOCS-GEOPANDAS**, o site acabou caindo.  Alguém poderia dizer o que eu fiz de errado?

**Comment by M3nin0** [comment]
Verificando aqui os arquivos que estão no diretório `docs`, que são utilizados para fazer o deploy do site, a nomenclatura deles acabou ficando diferente.

Então, o que está sendo pesquisado como `introducao.html`, acabou sendo gerado como `introdução.html`.

Mudei os nomes dos links e voltou a funcionar. Pode ser que este comportamento tenha sido causado por alguma questão de versão ou algo assim, mas tudo bem. Se necessário, depois que todo o conteúdo for inserido eu gero as páginas da documentação.
